SRT-26: Update header and footer styling
keep-network/website pull request #356
Opened 2021-04-06 20:22 UTC by maymax777

- Fix minor style issue

2021-04-08 10:00 UTC, FrozenIce0617 requested changes

2021-04-08 10:00 UTC, FrozenIce0617 commented on src/css/button.scss
> +.btn {
@maymax777 , class `btn` has already been defined in Bootstrap. You can define custom styles as `a.button` on the top.

2021-04-09 10:56 UTC, FrozenIce0617 requested changes

2021-04-09 10:56 UTC, FrozenIce0617 commented on src/css/button.scss
> +  display: flex;
@maymax777, As I mentioned in Slack channel, we can customize the button style based on bootstrap like as following:
```
a.button {
  @extend .btn;
  ... // additional styles here
  &-primary {
    @extend .btn-primary;
    ... // additional styles here
  }
  &-secondary {
    @extend .btn-secondary;
    ... // additional styles here
  }
  &-full-width {
    width: 100%;
  }
  &-sm {
    width: 120px;
    height: 54px;
  }
}
```

2021-04-09 12:59 UTC, FrozenIce0617 approved these changes

2021-04-09 13:25 UTC, micahjlucas approved these changes

2021-04-09 13:25 UTC, merged