(WIP) SRT-4: Create initial build page
keep-network/website pull request #357
Opened 2021-04-06 20:37 UTC by maymax777

- Create initial build page template

2021-04-09 15:08 UTC, micahjlucas requested changes
Code looks good overall, just added a couple comments.

2021-04-09 15:08 UTC, micahjlucas commented on src/css/v2/carousel.scss
> +    // background-position-x: 293px;
Please remove or add comment message.

2021-04-09 15:08 UTC, micahjlucas commented on src/pages/v2/build.md
> +template: v2-build-page
Should probably remove v2 here, since that directory is removed.

2021-04-09 15:08 UTC, micahjlucas commented on src/templates/v2-build-page.js
> +const carousel1 = {
Please rename to something more descriptive - Example: `carouselBuild`

2021-04-14 04:17 UTC, maymax777 commented
Duplicated from #367

2021-04-14 04:17 UTC, closed without merging