Feat(UI)/SRT-36: News-Press
keep-network/website pull request #383
Opened 2021-04-19 08:58 UTC by astanovferuz

Added 2021 to "filter by year" on News-Press page as well as it's active indicator

2021-04-19 13:31 UTC, micahjlucas requested changes

2021-04-19 13:31 UTC, micahjlucas commented on src/css/press.scss
> +                border-bottom: 0;;
Extra colon here: please remove.

2021-04-20 12:33 UTC, FrozenIce0617 approved these changes
LGTM!

2021-04-20 13:54 UTC, micahjlucas approved these changes

2021-04-20 13:54 UTC, merged