Feat(UI)/SRT-73: Keep UI feedback info-page missing image
keep-network/website pull request #419
Opened 2021-05-11 15:27 UTC by astanovferuz

Image is set and the section responsiveness is fixed.

2021-05-11 20:33 UTC, micahjlucas approved these changes
@astanovferuz Looks good on my side 💥 

Please allow @FrozenIce0617 to review and feel free to merge after.

2021-05-12 10:49 UTC, FrozenIce0617 requested changes

2021-05-12 10:49 UTC, FrozenIce0617 commented on src/css/info.scss
> +      @media (max-width: #{$bp-large}) {
@astanovferuz, As I mentioned yesterday, for the `max-width`, it should smaller `$bp-large - 1`.

2021-05-12 10:49 UTC, FrozenIce0617 commented on src/css/info.scss
> +          font-size: 45px;
`font-size` and `line-height` are already defined in global. Don't need to redefine it in here.

2021-05-12 10:49 UTC, FrozenIce0617 commented on src/css/info.scss
> +          font-size: 18px;
`font-size` and `line-height` are already defined in global. Don't need to redefine it in here.

2021-05-12 11:52 UTC, FrozenIce0617 approved these changes
LGTM!

2021-05-12 12:35 UTC, micahjlucas approved these changes

2021-05-12 12:35 UTC, merged