Feat(UI)/SRT-75: Keep general UI review and code cleanup
keep-network/website pull request #422
Opened 2021-05-12 13:21 UTC by astanovferuz

Stake page: Tech guide title and body font adjusted for smaller screen sizes
Stake page: "Why stake" section cards size and responsiveness adjusted for medium screens
Stake page: "Recommended staking providers" section cards title and responsiveness adjusted for medium screen sizes
Info page: "The keep solution" section cards size and responsiveness adjusted for medium screen sizes
Info page: "Securing keep" section cards size and responsiveness adjusted for medium screen sizes

2021-05-12 14:30 UTC, FrozenIce0617 approved these changes

2021-05-12 14:30 UTC, FrozenIce0617 commented on src/css/info.scss
> +      @media (max-width: #{$bp-large}) {
@astanovferuz , this changes should applied between medium and large size. So, the media should be:
```
@media (min-width: #{$bp-medium}) and (max-width: #{$bp-large - 1}) {
```

2021-05-12 14:30 UTC, FrozenIce0617 commented on src/css/info.scss
> +      @media (max-width: #{$bp-large}) {
Same here:
```
@media (min-width: #{$bp-medium}) and (max-width: #{$bp-large - 1}) {
```

2021-05-12 14:30 UTC, FrozenIce0617 commented on src/css/stake-page.scss
> +        @media (max-width: #{$bp-large}) {
Same here:
```
@media (min-width: #{$bp-medium}) and (max-width: #{$bp-large - 1}) {
```

2021-05-12 14:30 UTC, FrozenIce0617 commented on src/css/stake-page.scss
> +            @media (max-width: #{$bp-extra-large}) {
Same here:
```
@media (min-width: #{$bp-large}) and (max-width: #{$bp-extra-large - 1}) {
```

2021-05-12 14:30 UTC, FrozenIce0617 commented on src/css/stake-page.scss
> +        @media (max-width: #{$bp-large}) {
Same here:
```
@media (min-width: #{$bp-medium}) and (max-width: #{$bp-large - 1}) {
```

2021-05-12 15:10 UTC, micahjlucas requested changes
Pausing until Robert's suggestions are confirmed.

2021-05-13 12:45 UTC, FrozenIce0617 approved these changes
LGTM!

2021-05-13 12:56 UTC, micahjlucas approved these changes

2021-05-13 12:56 UTC, merged